version: '2'
services:
    django:
        build:
            context: .
            dockerfile: ./docker_files/django/Dockerfile
        # restart: always
        command: python manage.py runserver 0.0.0.0:8000
        stdin_open: true
        tty: true
        volumes:
            - .:/django
        ports:
            - "8000:8000"
        links:
            - database
            #- webapp
        environment:
            DEBUG: "true"
            DATABASE_NAME: django
            DATABASE_USER: django
            DATABASE_PASSWORD: django
            DATABASE_SERVICE_HOST: database
    database:
        image: postgres:latest
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: django
    #webapp:
    #    build:
    #        context: .
    #        dockerfile: ./webapp/Dockerfile
    #    command: node server.js
    #    volumes:
    #        - .:/django
    #    ports:
    #        - "3000:3000"
volumes:
    pgdata: {}
